
[project]
dependencies = [
    "requests",
    "apprise",
    "colorama",
    "colorlog",
    "json5",
    "beautifulsoup4",
    "chardet==5.2.0",
    "rsa",
    "qrcode[pil]",
    "qrcode-terminal",
    "PyCryptodome",
    "protobuf",
    "PySocks",
    "schedule",
    "pytz",
    "pydantic",
    "requests-toolbelt",
    "tqdm",
]
requires-python = ">=3.12"

[dependency-groups]
build = [
    "pyinstaller>=6.22.2; python_version < '3.16'",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
